M48
; DRILL file {KiCad 9.0.2} date 2025-06-02T23:01:08+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-02T23:01:08+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C2.000
%
G90
G05
T1
X43.0Y-36.0
X44.5Y-37.0
T2
X26.92Y-36.5
X29.46Y-36.5
X32.0Y-36.5
X34.54Y-36.5
T3
X45.5Y-35.0
X50.0Y-35.0
M30
